secret: 123456
expire_time: 86400000

spring:
  http:
    multipart:
      maxFileSize: 20Mb
      maxRequestSize: 100Mb

zuul:
  sensitive-headers:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:  # routes to serviceId
    manager-ribbon-server-feign:
      path: /manager/**
      serviceId: manager-ribbon-server
    manager-ribbon-server-feign-url:
      path: /manager/**
      url: http://localhost:3200/




