
#应用的名字
spring:

#Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0 # Redis数据库索引（默认为0）
    pool:
      max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 5 # 连接池中的最小空闲连接
      timeout: 0 # 连接超时时间（毫秒）

